### ISSUE TITLE
[Umbrella] v7 Stable Release

### ISSUE THREAD

**Issue by tannerlinsley** [tannerlinsley/react-table#1964]
This is a list of all other issues or features that need to get checked off to make a release. If you have suggestions, please comment them below.

- [x] Fix row-selection bug (https://github.com/tannerlinsley/react-table/issues/1900)
- [x] Consider Col/Row-span plugin requirements (not the actual plugin) (https://github.com/tannerlinsley/react-table/issues/1342, https://github.com/tannerlinsley/react-table/issues/1933) (Non v7 release, but soon after hopefully)
- [x] Ensure no infiniite rendering loops like in https://github.com/tannerlinsley/react-table/issues/1911
- [x] Ensure prop getter utilities and column decorators can and will generate stable callbacks and values (https://github.com/tannerlinsley/react-table/issues/1936)
- [x] See https://github.com/tannerlinsley/react-table/issues/1957 through
- ~Plugin Development Guide~ (https://github.com/tannerlinsley/react-table/issues/1969)
- [ ] `npm publish 7.0.0`

**Comment by liberza** [comment]
One thing that would be nice to have with a release is the Plugin Guide referenced in [docs/api/README.md](https://github.com/tannerlinsley/react-table/blob/master/docs/api/README.md). Does this already exist and I just haven't been able to find it?

**Comment by riceboyler** [comment]
It would be really nice if you were to "code freeze" for a week before the final release so we can update the associated @types/react-table repo to match, so that when it release, types are available. Obviously not a requirement, but it might make things nicer for those of us who are TS users. :)

**Comment by tannerlinsley** [comment]
Given that there hasn't been much turmoil in the source for the last few weeks, I would say yes to that idea, but only for a day or two (assuming there are not many more public API/type changes). If anyone is waiting to update the types, they should do as much as they can now, as things are becoming pretty stable.

**Comment by riceboyler** [comment]
OK, I'll get to work on updating the types for my PR that got merged Friday and take a look around to see what (if anything) I missed.

**Comment by andreizhvaleuski** [comment]
Do you fixed this problem with pagination (7.0.0-rc.16)?
![image](https://user-images.githubusercontent.com/30213401/76292780-e301a480-62c0-11ea-86c4-4c356c269a74.png)

**Comment by valentyna-refundit** [comment]
It would be great if you looked at working with dates: [Spectrum link](https://spectrum.chat/react-table/general/use-original-for-datetime-sorting~e1db4709-b255-400f-b7f0-3d7414f281b5), [Second spectrum link](https://spectrum.chat/react-table/general/example-for-sorttype-with-datetime-or-custom-function-date~95d5550b-977e-4ece-84df-c8bf3a568afe)
_or added an example of how you expect to work with dates_

Thanks in advance!

**Comment by riceboyler** [comment]
> Second spectrum link

@valentyna-refundit We're using dates, but formatting them before they get passed in to the `data` prop, which makes it much easier to manage. I think date manipulation/formatting is probably outside the scope of what react-table itself does.

**Comment by tannerlinsley** [comment]
> Did you fix this problem with pagination (7.0.0-rc.16)?
> ![image](https://user-images.githubusercontent.com/30213401/76292780-e301a480-62c0-11ea-86c4-4c356c269a74.png)

Yes we did.

**Comment by tannerlinsley** [comment]
> It would be great if you looked at working with dates: [Spectrum link](https://spectrum.chat/react-table/general/use-original-for-datetime-sorting~e1db4709-b255-400f-b7f0-3d7414f281b5), [Second spectrum link](https://spectrum.chat/react-table/general/example-for-sorttype-with-datetime-or-custom-function-date~95d5550b-977e-4ece-84df-c8bf3a568afe)
> _or added an example of how you expect to work with dates_
> 
> Thanks in advance!

I've responded here. If you would like to add a PR to the docs with this information where you see it fits best, I would gladly accept that PR :)

https://spectrum.chat/react-table/general/use-original-for-datetime-sorting~e1db4709-b255-400f-b7f0-3d7414f281b5

**Comment by tannerlinsley** [comment]
I'm going to remove the plugin guide from this list and add as an issue. I think it's a great idea and should be top of mind post launch, but technically it is not a requirement for people to use React Table and thus I don't want it to be a blocker for a stable release.

**Comment by tannerlinsley** [comment]
Alright. I'm going to be prepping the release (media, tweets, etc) for the end of today (3 hours ish). I know this is quick, but I'm headed out of town and don't really want to delay any longer. Thanks for all of your help everyone!
